[versions]
agp = "8.4.0"
kotlin = "1.9.0"
coreKtx = "1.13.0"
junit5 = "5.10.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.7.0"
activityCompose = "1.9.0"
composeBom = "2023.08.00"
googleFonts = "1.7.0-alpha07"
koinVersion = "3.6.0-wasm-alpha2"
graphicsShapesAndroid = "1.0.0-alpha05"
graphicsPathAndroid = "1.0.0"
graphicsCoreAndroid = "1.0.0-rc01"
navigationCompose = "2.7.7"
riveAndroidVersion = "8.7.0"
startupRuntimeVersion = "1.1.1"
zxingVersion = "3.5.3"
cameraxVerion = "1.4.0-beta02"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
jupiter-junit5 = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit5" }
jupiter-engine-junit5 = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit5" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "googleFonts" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koinVersion" }
androidx-graphics-shapes-android = { group = "androidx.graphics", name = "graphics-shapes-android", version.ref = "graphicsShapesAndroid" }
androidx-graphics-path-android = { group = "androidx.graphics", name = "graphics-path", version.ref = "graphicsPathAndroid" }
androidx-graphics-core-android = { group = "androidx.graphics", name = "graphics-core", version.ref = "graphicsCoreAndroid" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
rive-android = { group = "app.rive", name = "rive-android", version.ref = "riveAndroidVersion" }
androidx-startup-runtime = { group = "androidx.startup", name = "startup-runtime", version.ref = "startupRuntimeVersion" }
google-zxing = { group = "com.google.zxing", name = "core", version.ref = "zxingVersion" }
camerax-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraxVerion" }
camerax-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "cameraxVerion" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

